### PR TITLE
Send off Viren & Chillar

### PR DESCRIPTION
**Pull request by dhilipsiva**
@viren-nadkarni (The Gratefully Graceful Goan Guy a.k.a G4) @ChillarAnand (The mysterious guy - for all we know might be an alien in disguise) Its has been awesome having you guys here @appknox. It's been an absolute joy working with the both of you. All the movies that we went to, all the things that we built as a team at Appknox, all the plants that we planted in our garden and for all the parties we had on Fridays - I wish we had more time together. But change is the only constant. You guys will be missed very deeply. This is a void that can never be filled by anyone else. So the next time you get a chance to visit us - please use the chance. All the very best for your future endeavour. Adios Amigos :kiss:

### CODE REVIEW

**Comment by dhilipsiva** [comment]
(scrum

https://dino.xyz/appknox/po-1033

**Comment by subho007** [comment]
@ChillarAnand @viren-nadkarni Thank you for being there with us. It has been our pleasure in Appknox to be working with you guys. I know you will reach great heights. And never forget us. You both will be like our family forever 😘

**Comment by dhilipsiva** [comment]
Funny thing is, @ChillarAnand came so close to beating me in mycroft contributions. Sad thing you are leaving when you are just days away from it 😛 
screen shot 2017-07-19 at 13 39 48

**Comment by mani8866** [comment]
@viren-nadkarni  @ChillarAnand It was very good with working you guys.You have been always helping us with a lot of patience .Wish you guys a good luck for your future

**Comment by vaishaligarg18** [comment]
@ChillarAnand @viren-nadkarni It was great working with u guys. All the very best for your future endeavours

**Comment by morsajagadeesh** [comment]
@viren-nadkarni and @ChillarAnand , with in a very less time you guys helped me a lot and I felt very happy & comfortable to work with you. All the best for your future projects and Keep ROCKING as always 👍

**Pull request merged**
